force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Company details</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Average_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Rating__c</fullName>
    <description>Average rating of the company given by employees</description>
    <label>Average Rating</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Employee details</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company that the employee works at</description>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <description>Rating of the company given by the employee</description>
    <inlineHelpText>Rating of the company</inlineHelpText>
    <label>Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EmployeeRatingTriggerHandler.cls
public with sharing class EmployeeRatingTriggerHandler {
    public EmployeeRatingTriggerHandler() {

    }

    public static void handleEmployeeUdpate(Employee__c[] employees) {
        for(Employee__c employee : employees) {
            updateCompanyRating(employee.company__c);
        }

    }

    public static void updateCompanyRating(ID company){
        Decimal sum = 0;
        Employee__c[] empList = [SELECT name, rating__c FROM employee__c WHERE company__c = :company];
        for(Employee__c employee : empList){
            sum = sum + employee.rating__c;
        }
        System.debug('Employee avg: ' + sum/empList.size());
        Company__c comp = [SELECT id, name, Average_Rating__c FROM Company__c WHERE id = :company];
        comp.Average_Rating__c = sum/empList.size();
        update comp;
    }
}